### PR TITLE
Breaking change from v3: make locutil prefer newer APIs

### PR DESCRIPTION
**Pull request by rseanhall**
Make LocProbeForFile use TRUE for fUseUILanguage
Never use ::GetUserDefaultLangID()

### CODE REVIEW

**Review by robmen — COMMENTED** [review]
I'm not the best one to comment on this. @bmurri and @barnson know more about loc. I was just trying to port changes that I thought were lost.

**Comment by rseanhall** [comment]
For context: https://github.com/wixtoolset/dutil/commit/b2c4600453f926fbfdc63219126930ad39601f25#r49579177

> What was the reason for porting LocProbeForFileEx? This is a breaking change, I think v4 was purposely only using the new APIs.

**Comment by BMurri** [comment]
In v4, there shouldn't be a need for `fUseUILanguage`, because that flag should never be false. No need to test for it, just don't have it. The presence of the flag would allow incorrect usage of the relevant APIs to occur.

**Comment by BMurri** [comment]
> I'm not the best one to comment on this. @BMurri and @barnson know more about loc. I was just trying to port changes that I thought were lost.

5-6 years ago I supplied separate PRs to v3 and v4 to attempt to eliminate the possibility in v4 that this would be messed up again,

**Comment by robmen** [comment]
> 5-6 years ago I supplied separate PRs to v3 and v4 to attempt to eliminate the possibility in v4 that this would be messed up again,

My mistake. I remembered incorrectly and ported this change with other changes from `wix3`. I'll undo.

**Pull request closed without merging**
